PHI instruction need arguments but 0 was given

Traceback (most recent call last):
  File "conkas.py", line 114, in main
    traces = sym_exec.execute()
  File "/conkas/sym_exec/symbolic_executor.py", line 51, in execute
    new_traces = self.__sym_exec_traces(traces_to_execute)
  File "/conkas/sym_exec/symbolic_executor.py", line 64, in __sym_exec_traces
    new_blocks = self.__sym_exec_block(block_to_analyse, trace.state)
  File "/conkas/sym_exec/symbolic_executor.py", line 93, in __sym_exec_block
    new_blocks = self.__sym_exec_instruction(instruction, state)
  File "/conkas/sym_exec/symbolic_executor.py", line 116, in __sym_exec_instruction
    return func(instruction, state)
  File "/conkas/sym_exec/instructions/rattle_instructions.py", line 58, in inst_phi
    raise Exception
Exception
ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2
ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2
Analysing /sb/MainToken.sol:BEP20...
Nothing to analyse
Analysing /sb/MainToken.sol:BEP20Basic...
Nothing to analyse
Analysing /sb/MainToken.sol:BasicToken...
Analysing /sb/MainToken.sol:BurnableToken...
Analysing /sb/MainToken.sol:Consts...
Analysing /sb/MainToken.sol:FreezableMintableToken...
Analysing /sb/MainToken.sol:FreezableToken...
Vulnerability: Integer Overflow. Maybe in function: balanceOf(address). PC: 0x151d. Line number: 398.
If a = 1
and b = 115792089237316195423570985008687907853269984665640564039457584007913129639935
Vulnerability: Time Manipulation. Maybe in function: releaseAll(). PC: 0x120b. Line number: 471.
Analysing /sb/MainToken.sol:MainToken...
Analysing /sb/MainToken.sol:MintableToken...
Analysing /sb/MainToken.sol:Ownable...
Analysing /sb/MainToken.sol:Pausable...
Analysing /sb/MainToken.sol:SafeMath...
Analysing /sb/MainToken.sol:StandardToken...
